name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with dockerr 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Heloo World"
      - name: Log node version 2
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Some Strings"
  node-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ivanaugusto9
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull image from DockerHub
        run: docker pull ivanaugusto9/axe-test-guia:latest

      - name: Run image in container
        run: docker run -it --rm ivanaugusto9/axe-test-guia:latest https://coffeentech.com.br/