name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: ivanaugusto9/axe-test-guia:latest
      options: --user 1001
      credentials:
        username: ivanaugusto9
        password: ${{  secrets.DOCKER_PASSWORD }}
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Heloo World"
      - name: Log node version 2
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release